In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/survey_results_public.csv')
schema_df = pd.read_csv('data/survey_results_schema.csv')

In [3]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [4]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [5]:
df['ConvertedComp'].head(15)

0          NaN
1          NaN
2       8820.0
3      61000.0
4          NaN
5     366420.0
6          NaN
7          NaN
8      95179.0
9      13293.0
10         NaN
11         NaN
12     90000.0
13     57060.0
14         NaN
Name: ConvertedComp, dtype: float64

In [6]:
df['ConvertedComp'].median()

57287.0

In [7]:
df.median()

Respondent       44442.0
CompTotal        62000.0
ConvertedComp    57287.0
WorkWeekHrs         40.0
CodeRevHrs           4.0
Age                 29.0
dtype: float64

In [8]:
df.describe()

,Respondent,CompTotal,ConvertedComp,WorkWeekHrs,CodeRevHrs,Age
count,88883.000000,5.594500e+04,5.582300e+04,64503.000000,49790.000000,79210.000000
mean,44442.000000,5.519014e+11,1.271107e+05,42.127197,5.084308,30.336699
std,25658.456325,7.331926e+13,2.841523e+05,37.287610,5.513931,9.178390
min,1.000000,0.000000e+00,0.000000e+00,1.000000,0.000000,1.000000
25%,22221.500000,2.000000e+04,2.577750e+04,40.000000,2.000000,24.000000
50%,44442.000000,6.200000e+04,5.728700e+04,40.000000,4.000000,29.000000
75%,66662.500000,1.200000e+05,1.000000e+05,44.750000,6.000000,35.000000
max,88883.000000,1.000000e+16,2.000000e+06,4850.000000,99.000000,99.000000

In [9]:
df['ConvertedComp'].count()

55823

In [10]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [11]:
df['Hobbyist'].value_counts()

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [12]:
df['SocialMedia']

0          Twitter
1        Instagram
2           Reddit
3           Reddit
4         Facebook
           ...
88878      YouTube
88879          NaN
88880          NaN
88881          NaN
88882     WhatsApp
Name: SocialMedia, Length: 88883, dtype: object

In [ ]:
schema_df.loc['SocialMedia']

In [22]:
df['SocialMedia'].value_counts()

Reddit                      14374
YouTube                     13830
WhatsApp                    13347
Facebook                    13178
Twitter                     11398
Instagram                    6261
I don't use social media     5554
LinkedIn                     4501
WeChat 微信                     667
Snapchat                      628
VK ВКонта́кте                 603
Weibo 新浪微博                     56
Youku Tudou 优酷                 21
Hello                          19
Name: SocialMedia, dtype: int64

In [23]:
df['SocialMedia'].value_counts(normalize=True)

Reddit                      0.170233
YouTube                     0.163791
WhatsApp                    0.158071
Facebook                    0.156069
Twitter                     0.134988
Instagram                   0.074150
I don't use social media    0.065777
LinkedIn                    0.053306
WeChat 微信                   0.007899
Snapchat                    0.007437
VK ВКонта́кте               0.007141
Weibo 新浪微博                  0.000663
Youku Tudou 优酷              0.000249
Hello                       0.000225
Name: SocialMedia, dtype: float64

In [24]:
df['Country']

0                United Kingdom
1        Bosnia and Herzegovina
2                      Thailand
3                 United States
4                       Ukraine
                  ...
88878                    Canada
88879                       NaN
88880                       NaN
88881                       NaN
88882                     Spain
Name: Country, Length: 88883, dtype: object

In [25]:
df['Country'].value_counts()

United States                       20949
India                                9061
Germany                              5866
United Kingdom                       5737
Canada                               3395
                                    ...
Saint Kitts and Nevis                   1
Saint Vincent and the Grenadines        1
Sao Tome and Principe                   1
Timor-Leste                             1
Tonga                                   1
Name: Country, Length: 179, dtype: int64

In [27]:
country_grp = df.groupby(['Country'])

In [29]:
country_grp.get_group('Poland')

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
51,52,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Poland,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",20 to 99 employees,"Developer, back-end;DevOps specialist",12,8,1,Very satisfied,Slightly satisfied,Very confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,NaN,No,NaN,I was preparing for a job search,PLN,Polish zloty,12320.0,Monthly,39504.0,40.0,There's no schedule or spec; I work on what se...,Meetings;Time spent commuting,Less than once per month / Never,Office,A little above average,"Yes, because I was told to do so",4.0,"Yes, it's part of our process",Developers typically have the most influence o...,I have some influence,Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;H...,Rust,MariaDB;PostgreSQL;SQLite,PostgreSQL;SQLite,Linux,Linux,Other(s):,Other(s):,Node.js,NaN,IntelliJ;Visual Studio Code,Linux-based,I do not use containers,Accepting Bitcoin or other coins and tokens as...,"Useful for decentralized currency (i.e., Bitcoin)",No,SIGH,Yes,NaN,Neither,Username,2011,Less than once per month or monthly,Find answers to specific questions,Less than once per week,NaN,0-10 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","No, not really",A lot less welcome now than last year,NaN,22.0,Man,No,NaN,NaN,No,Appropriate in length,Neither easy nor difficult
80,81,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Poland,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Developer, full-stack",20,7,5,Very satisfied,Very satisfied,Very confident,No,No,I am not interested in new job opportunities,1-2 years ago,Write any code;Interview with people in peer r...,No,Industry that I'd be working in;Opportunities ...,I was preparing for a job search,PLN,Polish zloty,NaN,NaN,NaN,NaN,NaN,NaN,Less than once per month / Never,Office,Far above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,Assembly;Bash/Shell/PowerShell;C;C++;Python,Assembly;Bash/Shell/PowerShell;C;C++,NaN,NaN,Android;Arduino;Linux;Raspberry Pi,Android;Arduino;Linux;Raspberry Pi,NaN,NaN,NaN,NaN,Vim,Linux-based,I do not use containers,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Yes,No,I don't use social media,In real life (in person),Username,2011,A few times per month or weekly,Find answers to specific questions,Less than once per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, I've heard of them, but I am not part of a...","No, not at all",Just as welcome now as I felt last year,Tech meetups or events in your area,28.0,Man,No,NaN,White or of European descent,No,Appropriate in length,Easy
190,192,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Poland,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)",Mathematics or statistics,Taken an online course in programming or softw...,10 to 19 employees,Data scientist or machine learning specialist;...,6,13,2,Slightly dissatisfied,Slightly dissatisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Write any code;Interview with people in peer r...,No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,PLN,Polish zloty,9000.0,Monthly,28860.0,40.0,There is a schedule and/or spec (made by me or...,Meetings;Not enough people for the workload,A few days each month,Office,A little above average,"Yes, because I see value in code review",2.0,"No, but I think we should",Not sure,I have some influence,Bash/Shell/PowerShell;JavaScript;Python,Bash/Shell/PowerShell;Python;Scala,Elasticsearch;PostgreSQL;Redis,Elasticsearch;PostgreSQL;Redis,Docker;Google Cloud Platform;Kubernetes;Linux;...,Docker;Google Cloud Platform;Kubernetes;Linux;...,Django;React.js,Django;React.js,NaN,NaN,Vim;Visual Studio Code,Linux-based,Development;Testing;Production;Outside of work...,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),NaN,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers,28.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
192,194,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Poland,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,"Developer, back-end;Developer, embedded applic...",11,17,5,Very satisfied,Slightly satisfied,Somewhat confident,Not sure,No,"I’m not actively looking, but I am open to new...",1-2 years ago,Write any code;Interview with people in peer r...,No,Specific department or team I'd be working on;...,I was preparing for a job search,PLN,Polish zloty,4000.0,Monthly,12828.0,40.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Meeting...,A few days each month,Office,A little above average,No,NaN,"No, but I think we should",Developers and management have nearly equal in...,I have some influence,Assembly;Bash/Shell/PowerShell;C;HTML/CSS;Java...,Bash/Shell/PowerShell;C;HTML/CSS;Java;PHP,MySQL,NaN,Arduino;Linux;Raspberry Pi;Windows;Other(s):,Linux;Raspberry Pi;Windows;Other(s):,jQuery,NaN,Node.js,NaN,IntelliJ;Notepad++;Vim;Visual Studio,Windows,I do not use containers,Not at all,A passing fad,Yes,Yes,What?,Twitter,Neither,Login,2014,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Not sure / can't remember,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Courses on technologies you're interested in,29.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
228,230,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Poland,NaN,Some college/university study without earning ...,"Information systems, information technology, o...",Taken an online course in programming or softw...,"10,000 or more employees","Developer, back-end;Developer, desktop or ente...",10,10,2,Slightly dissatisfied,Slightly dissatisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write any code;Write code by hand (e.g., on a ...",No,Office environment or company culture;Opportun...,"Something else changed (education, award, medi...",PLN,Polish zloty,NaN,Monthly,NaN,40.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Meetings;Time spe...,Less than once per month / Never,Office,A little below average,"Yes, because I see value in code review",2.0,"Yes, it's not part of our process but the deve...",Not sure,I have little or no influence,Bash/Shell/PowerShell;Go;Python,Bash/Shell/PowerShell;Go;Java;Python,Cassandra;MariaDB,MariaDB,Docker;Kubernetes;Linux;Windows,AWS;Docker;Kubernetes;Linux;Windows,NaN,NaN,Ansible,Ansible,Atom;IntelliJ;Notepad++;Vim,Windows,"Development;Production;Outside of work, for pe...",NaN,Useful across many domains and could change ma...,Yes,Also Yes,Yes,YouTube,Neither,Login,2010,Multiple times per day,Find answers to specific questions;Contribute ...,More than 10 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,NaN,Man,No,Straight / Heterosexual,White or of European descent,No,Too long,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88318,88871,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Poland,"Yes, part-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...","Taught yourself a new language, framework, or ...",20 to 99 employees,"Developer, back-end;Developer, embedded applic...",5,15,2,Very dissatisfied,Very dissatisfied,Very confident,Not sure,Not sure,I am not interested in new job opportunities,Less than a year ago,Solve a brain-teaser style puzzle,No,"Languages, frameworks, and other technologies ...","My job status changed (promotion, new job, etc.)",PLN,Polish zloty,5000.0,Monthly,16032.0,168.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Distrac...,A few days each month,Office,A little above average,"Yes, because I see value in code review",4.0,"No, but I think we should",Not sure,I have a great deal of influence,C++;C#;HTML/CSS;Java;JavaScript;Python;SQL;Typ...,Bash/Shell/PowerShell;C++;C#;HTML/CSS;Java;Jav...,Microsoft SQL Server;MySQL;PostgreSQL,Elasticsearch;Firebase;MongoDB;MySQL;PostgreSQ...,Android;Docker;Linux;Windows,AWS;Docker;Google Cloud Platform;Kubernetes;Li...,Angular/Angular.js;ASP.NET;Spring;Vue.js,Angular/Angular.js;ASP.NET;Spring;Vue.js,.NET Core;Node.js,Ansible;.NET Core;Node.js,IntelliJ;Notepad++;PyCharm;Visual Studio Code,Windows,Development;Testing;Production;Outside of work...,Not at all,NaN,Yes,SIGH,Yes,Reddit,In real life (in person),Username,2018,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was slightly faster,31-60 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Too long,Neither easy nor difficult
88431,18256,NaN,No,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Poland,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,Completed an industry certification program (e...,100 to 499 employees,Educator,NaN,NaN,NaN,NaN,NaN,Very confident,Not sure,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows,I do not use containers,NaN,NaN,No,"Fortunately, someone else has that title",What?,LinkedIn,In real life (in person),Username,2014,Less than once per month or monthly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,NaN,42.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Neither easy nor difficult
88449,22192,NaN,No,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Poland,No,NaN,"A natural science (ex. biology, chemistry, phy...",Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...",Academic researcher;Educator,12,7,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clojure;Elixir;Python;R;Scala,Other(s):,PostgreSQL;Other(s):,NaN,Docker;Linux;Slack,Docker;Linux;Slack,NaN,NaN,Apache Spark,Apache Spark,Atom;IPython / Jupyter;PyCharm;RStudio;Vim,Linux-based,Development;Testing;Production,NaN,An irresponsible use of resources,No,SIGH,Yes,WhatsApp,Neither,Handle,2011,A few times per week,Learn how to do things I didn’t necessarily lo...,Less than once per week,They were about the same,NaN,Yes,Daily or almost daily,Yes,"No, I've heard of them, but I am not part of a...",Neutral,A lot less welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy
88728,62177,NaN,Yes,Less than once per year,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Poland,NaN,"Secondary school (e.g. American high school, G...",NaN,NaN,"10,000 or more employees",NaN,More than 50 years,Older than 85,More than 50 years,NaN,NaN,Somewhat confident,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C++;C#;Clojur...,Assembly;Bash/Shell/PowerShell;C;C++;C#;Clojur...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,NaN,NaN,NaN,NaN,NaN,NaN,Eclipse;Emacs;Sublime Text;TextMate;Visual Stu...,NaN,I do not use containers,Non-currency applications of blockchain,Useful for immutable record keeping outside of...,Yes,"Fortunately, someone else has that title",What?,Hello,NaN,Login,2019,I have never visited Stack Overflow (before to...,NaN,Less than once per week,Stack Overflow was much faster,60+ minutes,NaN,NaN,"No, I didn't know that Stack Overflow had a jo...",Yes,"Yes, definitely",Not applicable - I did not use Stack Overflow ...,Courses on technologies you're interested in,NaN,NaN,NaN,NaN,White or of European descent,NaN,Appropriate in length,Difficult
88837,81994,NaN,Yes,Never,The quality of OSS and closed source software ...,Employed part-time,Poland,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, back-end;Scientist;Student",4,19,1,NaN,NaN,Somewhat confident,Not sure,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Erlang;Java;Python;SQL,Java;Python;Scala,Elasticsearch;MongoDB;Microsoft SQL Server;Pos...,Elasticsearch;MongoDB,Docker;Heroku;Raspberry Pi;Slack;Windows,Docker;Kubernetes,React.js,NaN,NaN,Apache Spark;Hadoop;Pandas;TensorFlow;Torch/Py...,Atom;IntelliJ;IPython / Jupyter;PyCharm,Linux-based,Development,NaN,NaN,No,SIGH,What?,Facebook,Online,Login,2015,Daily or almost daily,Find answers to specific questions;Learn how t...,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...",Neutral,NaN,NaN,22.0,Woman,No,NaN,White or of European descent,No,Too long,Easy

In [31]:
filt = df['Country'] == 'Poland'
df.loc[filt]['SocialMedia'].value_counts()

Facebook                    619
YouTube                     366
Reddit                      258
I don't use social media    180
Twitter                     164
Instagram                    86
LinkedIn                     72
WhatsApp                     64
Snapchat                      7
VK ВКонта́кте                 4
Hello                         1
Name: SocialMedia, dtype: int64

In [34]:
country_grp['SocialMedia'].value_counts().head(50)

Country              SocialMedia
Afghanistan          Facebook                     15
                     YouTube                       9
                     I don't use social media      6
                     WhatsApp                      4
                     Instagram                     1
                     LinkedIn                      1
                     Twitter                       1
Albania              WhatsApp                     18
                     Facebook                     16
                     Instagram                    13
                     YouTube                      10
                     Twitter                       8
                     LinkedIn                      7
                     Reddit                        6
                     I don't use social media      4
                     Snapchat                      1
                     WeChat 微信                     1
Algeria              YouTube                      42
                     Facebook                     41
                     Twitter                      14
                     LinkedIn                      9
                     I don't use social media      7
                     Instagram                     7
                     Reddit                        2
                     WhatsApp                      2
Andorra              Facebook                      2
                     I don't use social media      2
                     Reddit                        1
                     Snapchat                      1
                     YouTube                       1
Angola               Twitter                       2
                     Facebook                      1
                     YouTube                       1
Antigua and Barbuda  YouTube                       2
                     Facebook                      1
                     Instagram                     1
                     Twitter                       1
                     VK ВКонта́кте                 1
Argentina            WhatsApp                    202
                     Twitter                      80
                     YouTube                      62
                     Instagram                    53
                     Reddit                       50
                     Facebook                     45
                     I don't use social media     22
                     LinkedIn                     16
Armenia              Facebook                     38
                     YouTube                      23
                     LinkedIn                      5
                     Instagram                     3
Name: SocialMedia, dtype: int64

In [38]:
country_grp['SocialMedia'].value_counts(normalize=True).loc['Russian Federation']

SocialMedia
VK ВКонта́кте               0.303571
YouTube                     0.207418
I don't use social media    0.106456
Reddit                      0.096154
Twitter                     0.089286
Instagram                   0.064560
WhatsApp                    0.061813
Facebook                    0.046016
LinkedIn                    0.024038
Snapchat                    0.000687
Name: SocialMedia, dtype: float64

In [41]:
country_grp['ConvertedComp'].median().loc['Poland']

32064.0

In [42]:
country_grp['ConvertedComp'].median().loc['Germany']

63016.0

In [43]:
country_grp['ConvertedComp'].agg(['median', 'mean'])

                                        median           mean
Country
Afghanistan                             6222.0  101953.333333
Albania                                10818.0   21833.700000
Algeria                                 7878.0   34924.047619
Andorra                               160931.0  160931.000000
Angola                                  7764.0    7764.000000
...                                        ...            ...
Venezuela, Bolivarian Republic of...    6384.0   14581.627907
Viet Nam                               11892.0   17233.436782
Yemen                                  11940.0   16909.166667
Zambia                                  5040.0   10075.375000
Zimbabwe                               19200.0   34046.666667

[179 rows x 2 columns]

In [44]:
country_grp['ConvertedComp'].agg(['median', 'mean']).loc['Canada']

median     68705.000000
mean      134018.564909
Name: Canada, dtype: float64

In [48]:
filt = df['Country'] == 'Poland'
df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

751

In [49]:
country_grp['LanguageWorkedWith'].str.contains('Python').sum()

AttributeError: 'SeriesGroupBy' object has no attribute 'str'

In [50]:
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [51]:
country_respodents = df['Country'].value_counts()
country_respodents

United States                       20949
India                                9061
Germany                              5866
United Kingdom                       5737
Canada                               3395
                                    ...
Saint Kitts and Nevis                   1
Saint Vincent and the Grenadines        1
Sao Tome and Principe                   1
Timor-Leste                             1
Tonga                                   1
Name: Country, Length: 179, dtype: int64

In [52]:
country_uses_python = country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())
country_uses_python

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [55]:
python_df = pd.concat([country_respodents, country_uses_python], axis='columns', sort=False)

In [54]:
python_df

                                  Country  LanguageWorkedWith
United States                       20949               10083
India                                9061                3105
Germany                              5866                2451
United Kingdom                       5737                2384
Canada                               3395                1558
...                                   ...                 ...
Saint Kitts and Nevis                   1                   0
Saint Vincent and the Grenadines        1                   0
Sao Tome and Principe                   1                   1
Timor-Leste                             1                   1
Tonga                                   1                   0

[179 rows x 2 columns]

In [57]:
python_df.rename(columns={'Country': 'NumRespondents', 'LanguageWorkedWith': 'NumKnowsPython'}, inplace=True)

In [58]:
python_df

                                  NumRespondents  NumKnowsPython
United States                              20949           10083
India                                       9061            3105
Germany                                     5866            2451
United Kingdom                              5737            2384
Canada                                      3395            1558
...                                          ...             ...
Saint Kitts and Nevis                          1               0
Saint Vincent and the Grenadines               1               0
Sao Tome and Principe                          1               1
Timor-Leste                                    1               1
Tonga                                          1               0

[179 rows x 2 columns]

In [59]:
python_df['PctKnowsPython'] = (python_df['NumKnowsPython'] / python_df['NumRespondents']) * 100

In [60]:
python_df

,NumRespondents,NumKnowsPython,PctKnowsPython
United States,20949,10083,48.131176
India,9061,3105,34.267741
Germany,5866,2451,41.783157
United Kingdom,5737,2384,41.554820
Canada,3395,1558,45.891016
...,...,...,...
Saint Kitts and Nevis,1,0,0.000000
Saint Vincent and the Grenadines,1,0,0.000000
Sao Tome and Principe,1,1,100.000000
Timor-Leste,1,1,100.000000
Tonga,1,0,0.000000

In [62]:
python_df.sort_values(by='PctKnowsPython', ascending=False, inplace=True)

In [64]:
python_df.head(50)

,NumRespondents,NumKnowsPython,PctKnowsPython
Niger,1,1,100.000000
Dominica,1,1,100.000000
Timor-Leste,1,1,100.000000
Sao Tome and Principe,1,1,100.000000
Turkmenistan,7,6,85.714286
Mauritania,7,5,71.428571
Bahamas,3,2,66.666667
Guyana,3,2,66.666667
Guinea,3,2,66.666667
Uganda,72,47,65.277778
Iceland,49,30,61.224490
Benin,5,3,60.000000
Haiti,5,3,60.000000
Namibia,5,3,60.000000
"Congo, Republic of the...",7,4,57.142857
Oman,11,6,54.545455
Cuba,30,16,53.333333
Republic of Korea,39,20,51.282051
South Korea,160,80,50.000000
Sierra Leone,2,1,50.000000
Monaco,4,2,50.000000
Bhutan,2,1,50.000000
San Marino,2,1,50.000000
Seychelles,2,1,50.000000
Chile,206,102,49.514563
Finland,546,266,48.717949
Kenya,249,120,48.192771
United States,20949,10083,48.131176
Israel,952,457,48.004202
Ecuador,82,39,47.560976
Taiwan,187,88,47.058824
Mongolia,17,8,47.058824
Montenegro,17,8,47.058824
Switzerland,978,460,47.034765
United Republic of Tanzania,32,15,46.875000
Hong Kong (S.A.R.),188,88,46.808511
Japan,391,182,46.547315
Maldives,13,6,46.153846
Canada,3395,1558,45.891016
Singapore,303,139,45.874587
New Zealand,524,236,45.038168
China,664,297,44.728916
Honduras,27,12,44.444444
France,2391,1054,44.081974
Iraq,39,17,43.589744
Thailand,214,92,42.990654
Democratic Republic of the Congo,7,3,42.857143
Nepal,237,101,42.616034
Estonia,195,82,42.051282
Russian Federation,1694,708,41.794569

In [65]:
python_df.loc['Poland']

NumRespondents    1922.000000
NumKnowsPython     751.000000
PctKnowsPython      39.073881
Name: Poland, dtype: float64